export const INCREMENT = 'INCREMENT';
export const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
export const DECREMENT = 'DECREMENT';
export const DECREMENT_ASYNC = 'DECREMENT_ASYNC';
export const COUNTING_ASYNC_START = 'COUNTING_ASYNC_START';
export const COUNTING_ASYNC_SUCCESS = 'COUNTING_ASYNC_SUCCESS';
export const COUNTING_ASYNC_FAILURE = 'COUNTING_ASYNC_FAILURE';

// Start up actions


// Load all Chains and Stores
export const LOAD_CHAINS_AND_STORES_ASYNC = 'LOAD_CHAINS_AND_STORES_ASYNC';
export const LOAD_CHAINS_AND_STORES_START = 'LOAD_CHAINS_AND_STORES_START';
export const LOAD_CHAINS_AND_STORES_SUCCESS = 'LOAD_CHAINS_AND_STORES_SUCCESS';
export const LOAD_CHAINS_AND_STORES_FAILURE = 'LOAD_CHAINS_AND_STORES_FAILURE';

// Select Chain
export const SELECT_CHAIN = 'SELECT_CHAIN';

// Select simulation config
export const SELECT_SIMULATION_CONFIG = 'SELECT_SIMULATION_CONFIG';

// Select simulation store config
export const SELECT_SIMULATION_STORE_CONFIG = 'SELECT_SIMULATION_STORE_CONFIG';

// Select simulation sales Sources
export const SELECT_SIMULATION_SALES_SOURCE = 'SELECT_SIMULATION_SALES_SOURCE';

//set calendar value
export const SET_CALENDAR_VALUE = 'SET_CALENDAR_VALUE';


// Select Store
export const SELECT_STORE = 'SELECT_STORE';

// Clear All Selections
export const CLEAR_SELECTIONS = 'CLEAR_SELECTIONS';

// Select Planogram
export const SELECT_PLANOGRAM = 'SELECT_PLANOGRAM';

// Clear Selected Planogram
export const CLEAR_SELECTED_PLANOGRAM = 'CLEAR_SELECTED_PLANOGRAM';

//Set Edit Mode For Planograms
export const SET_EDIT_MODE_FOR_PLANOGRAMS = 'SET_EDIT_MODE_FOR_PLANOGRAMS';

// Set Zoom for Planogram
export const SET_ZOOM_FOR_PLANOGRAM = 'SET_ZOOM_FOR_PLANOGRAM';

// Set optimized product images
export const SET_PRODUCT_IMAGES = 'SET_PRODUCT_IMAGES';

// Load Configuration
export const LOAD_CONFIGURATIONS_FOR_STORE_ASYNC = 'LOAD_CONFIGURATIONS_FOR_STORE_ASYNC';
export const LOAD_CONFIGURATIONS_FOR_STORE_START = 'LOAD_CONFIGURATIONS_FOR_STORE_START';
export const LOAD_CONFIGURATIONS_FOR_STORE_SUCCESS = 'LOAD_CONFIGURATIONS_FOR_STORE_SUCCESS';
export const LOAD_CONFIGURATIONS_FOR_STORE_FAILURE = 'LOAD_CONFIGURATIONS_FOR_STORE_FAILURE';


// Load all Planogram for Configuration
export const LOAD_PLANOGRAMS_FOR_CONFIG_ASYNC = 'LOAD_PLANOGRAMS_FOR_CONFIG_ASYNC';
export const LOAD_PLANOGRAMS_FOR_CONFIG_START = 'LOAD_PLANOGRAMS_FOR_CONFIG_START';
export const LOAD_PLANOGRAMS_FOR_CONFIG_SUCCESS = 'LOAD_PLANOGRAMS_FOR_CONFIG_SUCCESS';
export const LOAD_PLANOGRAMS_FOR_CONFIG_FAILURE = 'LOAD_PLANOGRAMS_FOR_CONFIG_FAILURE';



// Load POS for Planogram
export const LOAD_POS_FOR_PLANOGRAM_ASYNC = 'LOAD_POS_FOR_PLANOGRAM_ASYNC';
export const FLATTEN_POS_FOR_PLANOGRAM_START = 'FLATTEN_POS_FOR_PLANOGRAM_START';
export const FLATTEN_POS_FOR_PLANOGRAM_SUCCESS = 'FLATTEN_POS_FOR_PLANOGRAM_SUCCESS';
export const FLATTEN_POS_FOR_PLANOGRAM_FAILURE = 'FLATTEN_POS_FOR_PLANOGRAM_FAILURE';

// Set POS for Planogram
export const SET_POS_FOR_PLANOGRAM_ASYNC = 'SET_POS_FOR_PLANOGRAM_ASYNC';
export const SET_POS_FOR_PLANOGRAM_START = 'SET_POS_FOR_PLANOGRAM_START';
export const SET_POS_FOR_PLANOGRAM_SUCCESS = 'SET_POS_FOR_PLANOGRAM_SUCCESS';
export const SET_POS_FOR_PLANOGRAM_FAILURE = 'SET_POS_FOR_PLANOGRAM_FAILURE';

// Flatten POS for Planogram
export const FLATTEN_POS_FOR_PLANOGRAM = 'FLATTEN_POS_FOR_PLANOGRAM';

// Set Selected Position
export const SET_SELECTED_PLANOGRAM_POSITION = 'SET_SELECTED_PLANOGRAM_POSITION'

// Set Selected Position
export const UNSELECT_PLANOGRAM_POSITION = 'UNSELECT_PLANOGRAM_POSITION'

// Replace Position Position
export const REPLACE_PLANOGRAM_POSITION = 'REPLACE_PLANOGRAM_POSITION'

// Update the units for a position
export const UPDATE_PLANOGRAM_POSITION_UNITS = 'UPDATE_PLANOGRAM_POSITION_UNITS'

// Update the available qty for a position
export const UPDATE_PLANOGRAM_POSITION_AVAILABLE_QTY = 'UPDATE_PLANOGRAM_POSITION_AVAILABLE_QTY'

// Set Activity
export const SET_CURRENT_ACTIVITY_TYPE = 'SET_CURRENT_ACTIVITY_TYPE'

// Set Sub Activity
export const SET_CURRENT_SUB_ACTIVITY_TYPE = 'SET_CURRENT_SUB_ACTIVITY_TYPE'

// Select Configuration
export const SELECT_CURRENT_CONFIGURATION = 'SELECT_CURRENT_CONFIGURATION';

// Set Inventory
export const SET_CURRENT_CONFIGURATION_INVENTORY = 'SET_CURRENT_CONFIGURATION_INVENTORY';

// Set Low Inventory
export const SET_CURRENT_CONFIGURATION_LOW_INVENTORY = 'SET_CURRENT_CONFIGURATION_LOW_INVENTORY';

// Set OOS Inventory
export const SET_CURRENT_CONFIGURATION_OOS_INVENTORY = 'SET_CURRENT_CONFIGURATION_OOS_INVENTORY';

// Set Planogram Sales Allocation
export const SET_CURRENT_CONFIGURATION_PLANOGRAM_SALES_ALLOCATION = 'SET_CURRENT_CONFIGURATION_PLANOGRAM_SALES_ALLOCATION';

// Set New Configuration
export const SET_NEW_CONFIGURATION = 'SET_NEW_CONFIGURATION';

// Set Save Configuration
export const SAVE_CURRENT_CONFIGURATION_ASYNC = 'SAVE_CURRENT_CONFIGURATION_ASYNC';
export const SAVE_CURRENT_CONFIGURATION_START = 'SAVE_CURRENT_CONFIGURATION_START';
export const SAVE_CURRENT_CONFIGURATION_SUCCESS = 'SAVE_CURRENT_CONFIGURATION_SUCCESS';
export const SAVE_CURRENT_CONFIGURATION_FAILURE = 'SAVE_CURRENT_CONFIGURATION_FAILURE';

// Set Save As Configuration
export const SAVE_AS_CURRENT_CONFIGURATION_ASYNC = 'SAVE_AS_CURRENT_CONFIGURATION_ASYNC';
export const SAVE_AS_CURRENT_CONFIGURATION_START = 'SAVE_AS_CURRENT_CONFIGURATION_START';
export const SAVE_AS_CURRENT_CONFIGURATION_SUCCESS = 'SAVE_AS_CURRENT_CONFIGURATION_SUCCESS';
export const SAVE_AS_CURRENT_CONFIGURATION_FAILURE = 'SAVE_AS_CURRENT_CONFIGURATION_FAILURE';

// Delete Current Configuration
export const DELETE_CURRENT_CONFIGURATION_ASYNC = 'DELETE_CURRENT_CONFIGURATION_ASYNC';
export const DELETE_CURRENT_CONFIGURATION_START = 'DELETE_CURRENT_CONFIGURATION_START';
export const DELETE_CURRENT_CONFIGURATION_SUCCESS = 'DELETE_CURRENT_CONFIGURATION_SUCCESS';
export const DELETE_CURRENT_CONFIGURATION_FAILURE = 'DELETE_CURRENT_CONFIGURATION_FAILURE';

// Set Uploaded File
export const SET_UPLOADED_FILE_START = 'SET_UPLOADED_FILE_START'
export const SET_UPLOADED_FILE_SUCCESS = 'SET_UPLOADED_FILE_SUCCESS'
export const SET_UPLOADED_FILE_FAILURE = 'SET_UPLOADED_FILE_FAILURE'

// File Upload
export const FILE_UPLOAD_START_ASYNC = 'FILE_UPLOAD_START';
export const FILE_UPLOAD_START = 'FILE_UPLOAD_START';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_FAILURE = 'FILE_UPLOAD_FAILURE';



// Authorization Actions
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';

// search products
export const LOAD_PRODUCTS_FOR_SEARCH_ASYNC = 'LOAD_PRODUCTS_FOR_SEARCH_ASYNC';
export const LOAD_PRODUCTS_FOR_SEARCH_START = 'LOAD_PRODUCTS_FOR_SEARCH_START';
export const LOAD_PRODUCTS_FOR_SEARCH_SUCCESS = 'LOAD_PRODUCTS_FOR_SEARCH_SUCCESS';
export const LOAD_PRODUCTS_FOR_SEARCH_FAILURE = 'LOAD_PRODUCTS_FOR_SEARCH_FAILURE';

// Get Template Name
export const GET_TEMPLATE_NAME_ASYNC = 'GET_TEMPLATE_NAME_ASYNC';
export const GET_TEMPLATE_NAME_START = 'GET_TEMPLATE_NAME_START';
export const GET_TEMPLATE_NAME_SUCCESS = 'GET_TEMPLATE_NAME_SUCCESS';
export const GET_TEMPLATE_NAME_FAILURE = 'GET_TEMPLATE_NAME_FAILURE';

// Set Save As Template
export const SAVE_AS_TEMPLATE_ASYNC = 'SAVE_AS_TEMPLATE_ASYNC';
export const SAVE_AS_TEMPLATE_START = 'SAVE_AS_TEMPLATE_START';
export const SAVE_AS_TEMPLATE_SUCCESS = 'SAVE_AS_TEMPLATE_SUCCESS';
export const SAVE_AS_TEMPLATE_FAILURE = 'SAVE_AS_TEMPLATE_FAILURE';

// Clear Template
export const CLEAR_TEMPLATE = 'CLEAR_TEMPLATE';

// Set Save Planogram For Pos
export const SAVE_PLANOGRAM_FOR_POS_ASYNC = 'SAVE_PLANOGRAM_FOR_POS_ASYNC';
export const SAVE_PLANOGRAM_FOR_POS_START = 'SAVE_PLANOGRAM_FOR_POS_START';
export const SAVE_PLANOGRAM_FOR_POS_SUCCESS = 'SAVE_PLANOGRAM_FOR_POS_SUCCESS';
export const SAVE_PLANOGRAM_FOR_POS_FAILURE = 'SAVE_PLANOGRAM_FOR_POS_FAILURE';

// Clear Replace Pos 
export const CLEAR_PLANOGRAM_FOR_POS = 'CLEAR_PLANOGRAM_FOR_POS';

// get products for back stock
export const LOAD_PRODUCTS_FOR_BACKSTOCK_ASYNC = 'LOAD_PRODUCTS_FOR_BACKSTOCK_ASYNC';
export const LOAD_PRODUCTS_FOR_BACKSTOCK_START = 'LOAD_PRODUCTS_FOR_BACKSTOCK_START';
export const LOAD_PRODUCTS_FOR_BACKSTOCK_SUCCESS = 'LOAD_PRODUCTS_FOR_BACKSTOCK_SUCCESS';
export const LOAD_PRODUCTS_FOR_BACKSTOCK_FAILURE = 'LOAD_PRODUCTS_FOR_BACKSTOCK_FAILURE';

// Update products for back stock
export const UPDATE_PRODUCTS_FOR_BACKSTOCK_ASYNC = 'UPDATE_PRODUCTS_FOR_BACKSTOCK_ASYNC';
export const UPDATE_PRODUCTS_FOR_BACKSTOCK_START = 'UPDATE_PRODUCTS_FOR_BACKSTOCK_START';
export const UPDATE_PRODUCTS_FOR_BACKSTOCK_SUCCESS = 'UPDATE_PRODUCTS_FOR_BACKSTOCK_SUCCESS';
export const UPDATE_PRODUCTS_FOR_BACKSTOCK_FAILURE = 'UPDATE_PRODUCTS_FOR_BACKSTOCK_FAILURE';

// Update product back stock quantity
export const UPDATE_PRODUCT_BACK_STOCK_QUANTITY = 'UPDATE_PRODUCT_BACK_STOCK_QUANTITY';

//CLear product backstock quantity
export const CLEAR_PRODUCT_BACKSTOCK_QUANTITY = 'CLEAR_PRODUCT_BACKSTOCK_QUANTITY';

//Set Notification
export const SET_NOTIFICATION = 'SET_NOTIFICATION';

//Set selected date
export const SELECT_DATE = 'SELECT_DATE';

//Set service config
export const SELECT_SERVICE_CONFIG = 'SELECT_SERVICE_CONFIG';

//Set comparison data
export const SET_COMPARISON_DATA = 'SET_COMPARISON_DATA';
export const SET_COMPARISON_TABLE = 'SET_COMPARISON_TABLE';

//Set filterBy dropdown
export const SET_FILTERBY_DROPDOWN = 'SET_FILTERBY_DROPDOWN';

//Set sortBy dropdown
export const SET_SORTBY_DROPDOWN = 'SET_SORTBY_DROPDOWN';

//Set compareBy dropdown
export const SET_COMPAREBY_DROPDOWN = 'SET_COMPAREBY_DROPDOWN';

//Set comparison single file filter Data
export const SET_COMPARISON_SINGLE_FILE_FILTER_DATA = 'SET_COMPARISON_SINGLE_FILE_FILTER_DATA';

//Simultaion Action Types

//Set simulation view
export const SET_SIMULATION_VIEW = 'SET_SIMULATION_VIEW';

//Set Simulation Configuration
export const LOAD_SIMULATION_CONFIG_START = 'LOAD_SIMULATION_CONFIG_START';
export const LOAD_SIMULATION_CONFIG_ASYNC = 'LOAD_SIMULATION_CONFIG_ASYNC';
export const LOAD_SIMULATION_CONFIG_SUCCESS = 'LOAD_SIMULATION_CONFIG_SUCCESS';
export const LOAD_SIMULATION_CONFIG_FAILURE = 'LOAD_SIMULATION_CONFIG_FAILURE';

// Select Tab for Simulation
export const SELECT_TAB_SIMULATION = 'SELECT_TAB_SIMULATION';

// Clear Tab for Simulation
export const CLEAR_TAB_SIMULATION_VIEW = 'CLEAR_TAB_SIMULATION_VIEW';

// Clear Tab for Simulation
export const CLEAR_TAB_SIMULATION = 'CLEAR_TAB_SIMULATION';


// Set Save Simulation Configuration
export const SAVE_SIMULATION_CONFIGURATION_ASYNC = 'SAVE_SIMULATION_CONFIGURATION_ASYNC';
export const SAVE_SIMULATION_CONFIGURATION_START = 'SAVE_SIMULATION_CONFIGURATION_START';
export const SAVE_SIMULATION_CONFIGURATION_SUCCESS = 'SAVE_SIMULATION_CONFIGURATION_SUCCESS';
export const SAVE_SIMULATION_CONFIGURATION_FAILURE = 'SAVE_SIMULATION_CONFIGURATION_FAILURE';


// Set Run Simulation
export const RUN_SIMULATION_ASYNC = 'RUN_SIMULATION_ASYNC';
export const RUN_SIMULATION_START = 'RUN_SIMULATION_START';
export const RUN_SIMULATION_SUCCESS = 'RUN_SIMULATION_SUCCESS';
export const RUN_SIMULATION_FAILURE = 'RUN_SIMULATION_FAILURE';
export const RUN_SIMULATION_DATA_TRANSFORM = 'RUN_SIMULATION_DATA_TRANSFORM';

// Set the Total Inventory
export const CALCULATE_TOTAL_INVENTORY = 'CALCULATE_TOTAL_INVENTORY';

// Set the Total Inventory
export const CLEAR_CALCULATE_TOTAL_INVENTORY = 'CLEAR_CALCULATE_TOTAL_INVENTORY';

//Set Transform data for comparison
export const SET_TRANSFORM_DATA_FOR_TABLE = 'SET_TRANSFORM_DATA_FOR_TABLE';

//Set search result for comparison
export const SET_SEARCH_RESULT_FOR_TABLE = 'SET_SEARCH_RESULT_FOR_TABLE';

//Set initial data
export const SET_INITITAL_DATA = 'SET_INITITAL_DATA';

//Set comparison inventory data
export const SET_COMPARISON_INVENTORY_DATA = 'SET_COMPARISON_INVENTORY_DATA';


//clear Comparison data
export const CLEAR_COMPARISON_DATA = 'CLEAR_COMPARISON_DATA';

//clear search result
export const CLEAR_SEARCH_DATA = 'CLEAR_SEARCH_DATA';


// Delete Simulation Configuration
export const DELETE_SIMULATION_CONFIGURATION_ASYNC = 'DELETE_SIMULATION_CONFIGURATION_ASYNC';
export const DELETE_SIMULATION_CONFIGURATION_START = 'DELETE_SIMULATION_CONFIGURATION_START';
export const DELETE_SIMULATION_CONFIGURATION_SUCCESS = 'DELETE_SIMULATION_CONFIGURATION_SUCCESS';
export const DELETE_SIMULATION_CONFIGURATION_FAILURE = 'DELETE_SIMULATION_CONFIGURATION_FAILURE';

//set backstock search result
export const SET_BACKSTOCK_SEARCH_RESULT = 'SET_BACKSTOCK_SEARCH_RESULT';

// Load all uploaded file status
export const LOAD_UPLOADED_FILE_STATUS_ASYNC = 'LOAD_UPLOADED_FILE_STATUS_ASYNC';
export const LOAD_UPLOADED_FILE_STATUS_START = 'LOAD_UPLOADED_FILE_STATUS_START';
export const LOAD_UPLOADED_FILE_STATUS_SUCCESS = 'LOAD_UPLOADED_FILE_STATUS_SUCCESS';
export const LOAD_UPLOADED_FILE_STATUS_FAILURE = 'LOAD_UPLOADED_FILE_STATUS_FAILURE';

// add plano
export const ADD_PLANOGRAM = 'ADD_PLANOGRAM';

// Save new planogram 
export const SAVE_NEW_PLANOGRAM_ASYNC = 'SAVE_NEW_PLANOGRAM_ASYNC';
export const SAVE_NEW_PLANOGRAM_START = 'SAVE_NEW_PLANOGRAM_START';
export const SAVE_NEW_PLANOGRAM_SUCCESS = 'SAVE_NEW_PLANOGRAM_SUCCESS';
export const SAVE_NEW_PLANOGRAM_FAILURE = 'SAVE_NEW_PLANOGRAM_FAILURE';

export const CHECK_FILE_UPLOAD_TYPE = 'CHECK_FILE_UPLOAD_TYPE';

// Delete Selected Template
export const DELETE_SELECTED_TEMPLATE_ASYNC = 'DELETE_SELECTED_TEMPLATE_ASYNC';
export const DELETE_SELECTED_TEMPLATE_START = 'DELETE_SELECTED_TEMPLATE_START';
export const DELETE_SELECTED_TEMPLATE_SUCCESS = 'DELETE_SELECTED_TEMPLATE_SUCCESS';
export const DELETE_SELECTED_TEMPLATE_FAILURE = 'DELETE_SELECTED_TEMPLATE_FAILURE';

// Save Associate Template
export const SAVE_ASSOCIATE_TEMPLATE_ASYNC = 'SAVE_ASSOCIATE_TEMPLATE_ASYNC';
export const SAVE_ASSOCIATE_TEMPLATE_START = 'SAVE_ASSOCIATE_TEMPLATE_START';
export const SAVE_ASSOCIATE_TEMPLATE_SUCCESS = 'SAVE_ASSOCIATE_TEMPLATE_SUCCESS';
export const SAVE_ASSOCIATE_TEMPLATE_FAILURE = 'SAVE_ASSOCIATE_TEMPLATE_FAILURE';